version: '2'

networks:
  web:
    external: false

services:
  reverse-proxy:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "2537:2537"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/liri/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /etc/liri/traefik/acme:/etc/traefik/acme
    networks:
      - web
    restart: on-failure
