log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  api:
    address: ":2537"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "info@liri.io"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: traefik_web
