logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "pierluigi.fiorini@liri.io"
  entryPoint = "https"
  storage = "/etc/traefik/acme/acme.json"
  acmeLogging = true
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "liri.io"
    sans = ["www.liri.io", "build.liri.io", "repo.liri.io"]

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  network = "traefik_web"
