---
- name: "Create state directory"
  file: path={{ buildbot_master.state_dir }} state=directory recurse=yes mode=0755
- name: "Create configuration directory"
  file: path={{ buildbot_master.config_dir }} state=directory recurse=yes mode=0755
- name: "Configuration"
  template: src=config.json.j2 dest={{ buildbot_master.config_file }} mode=0644
- name: "Install nginx snippet"
  copy: src=buildbot-master.conf dest={{ nginx.conf_path }}/snippets/buildbot-master.conf mode=0644
- name: "Container"
  shell: docker pull {{ buildbot_master.docker_image }}
