---
- name: "Create state directory"
  file: path={{ buildbot_master.state_dir }} state=directory recurse=yes mode=0755
- name: "Create configuration directory"
  file: path={{ buildbot_master.config_dir }} state=directory recurse=yes mode=0755
- name: "Configuration"
  template: src=config.json.j2 dest={{ buildbot_master.config_file }} mode=0644
- name: "Prepare systemd unit"
  template: src=buildbot-master.service.j2 dest=/etc/systemd/system/buildbot-master.service mode=0644
- name: "Container"
  shell: docker pull {{ buildbot_master.docker_image }}
- name: "Restart service"
  shell: systemctl enable buildbot-master.service && systemctl daemon-reload && systemctl restart buildbot-master.service
  #systemd: name=buildbot-master.service state=restarted enabled=True
