- name: "Copy configuration"
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} force={{ item.force }}
  loop:
    - { src: "image-manager.service", dest: "/etc/systemd/system/image-manager.service", mode: 644, force: 'yes' }
    - { src: "compose.yml", dest: "/etc/liri/image-manager/docker-compose.yml", mode: 644, force: 'yes' }
    - { src: "settings.yaml", dest: "/etc/liri/image-manager/settings.yaml", mode: 600, force: 'no' }

- name: "Restart service"
  shell: systemctl enable image-manager.service && systemctl daemon-reload && systemctl restart image-manager.service
  #systemd: name=image-manager.service state=restarted enabled=True
