---
- hosts: main
  become: yes
  become_method: sudo
  vars_files:
    - ../vars.yml
  tasks:
    - apt_repository:
      repo: "ppa:certbot/certbot"
    - name: Install package
      apt: name=certbot state=present
    - cron:
        name: Renew certificates
        minute: 0
        hour: 10
        user: root
        job: /usr/bin/certbot renew --pre-hook "systemctl stop docker@www" --post-hook "systemctl start docker@www"
        cron_file: ansible_letsencrypt-renew
