---
- hosts: main
  become: yes
  become_method: sudo
  vars_files:
    - ../vars.yml
  tasks:
    - name: Create nginx snippets directory
      file: path={{ nginx_conf_path }}/snippets state=directory recurse=yes mode=0755
    - name: Set up virtual hosts
      template:
        src: ../templates/nginx-vhosts.conf.j2
        dest: "{{ nginx_conf_path }}/nginx-vhosts.conf"
        mode: 0644
    - name: Install snippets
      copy:
        src: ../nginx/snippets/ssl.conf
        dest: "{{ nginx_conf_path }}/snippets/ssl.conf"
        mode: 0644
    - name: Install systemd unit
      template:
        src: ../templates/nginx.service.j2
        dest: /etc/systemd/system/docker@www.service
        mode: 0644
    - name: Start service
      shell: systemctl enable docker@www.service && systemctl restart docker@www.service
#      systemd:
#        name: docker.www.service
#        state: started
#        enabled: True
