---
- hosts: main
  become: yes
  become_method: sudo
  vars_files:
    - ../vars.yml
  tasks:
    - name: Create nginx snippets directory
      file: path={{ nginx_conf_path }}/snippets state=directory recurse=yes mode=0755
    - name: Create nginx secure directory
      file: path={{ nginx_conf_path }}/secure state=directory recurse=yes mode=0755
    - name: Set up virtual hosts
      template:
        src: ../templates/nginx-vhosts.conf.j2
        dest: "{{ nginx_conf_path }}/nginx-vhosts.conf"
        mode: 0644
    - name: Install ssl snippet
      copy:
        src: ../nginx/snippets/ssl.conf
        dest: "{{ nginx_conf_path }}/snippets/ssl.conf"
        mode: 0644
    - name: Install gzip snippet
      copy:
        src: ../nginx/snippets/gzip.conf
        dest: "{{ nginx_conf_path }}/snippets/gzip.conf"
        mode: 0644
    - name: Install expires snippet
      copy:
        src: ../nginx/snippets/expires.conf
        dest: "{{ nginx_conf_path }}/snippets/expires.conf"
        mode: 0644
    - name: Install docs snippet
      copy:
        src: ../nginx/snippets/docs.conf
        dest: "{{ nginx_conf_path }}/snippets/docs.conf"
        mode: 0644
    - name: Install repo.liri.io snippet
      copy:
        src: ../nginx/snippets/repo.liri.io.conf
        dest: "{{ nginx_conf_path }}/snippets/repo.liri.io.conf"
        mode: 0644
    - name: Install artifacts.htpasswd
      copy:
        src: ../nginx/secure/artifacts.htpasswd
        dest: "{{ nginx_conf_path }}/secure/artifacts.htpasswd"
        mode: 0644

    - name: Install buildbot-master snippet
      copy:
        src: ../nginx/snippets/buildbot-master.conf
        dest: "{{ nginx_conf_path }}/snippets/buildbot-master.conf"
        mode: 0644

    - name: Install www systemd unit
      template:
        src: ../templates/nginx.service.j2
        dest: /etc/systemd/system/docker@www.service
        mode: 0644
    - name: Start www service
      shell: systemctl enable docker@www.service && systemctl daemon-reload && systemctl restart docker@www.service
#      systemd:
#        name: docker@www.service
#        state: started
#        enabled: True
