---
- hosts: main
  become: yes
  become_method: sudo
  vars_files:
    - ../vars.yml
  tasks:
    - name: Create www root
      file: path={{ nginx_html_path }}/liri.io state=directory recurse=yes owner=liri group=liri mode=0755

    - name: Create docs root
      file: path={{ nginx_html_path }}/docs.liri.io state=directory recurse=yes owner=liri group=liri mode=0755

    - name: Create nginx logs directory for www
      file: path={{ nginx_logs_path }}/liri.io state=directory recurse=yes mode=0755

    - name: Create build root
      file: path={{ nginx_html_path }}/build.liri.io state=directory recurse=yes mode=0755
    - name: Create nginx logs directory for build
      file: path={{ nginx_logs_path }}/build.liri.io state=directory recurse=yes mode=0755
    - name: Copy favicon.ico for build.liri.io
      get_url:
        url: https://raw.githubusercontent.com/lirios/lirios.github.io/master/favicon.ico
        dest: "{{ nginx_html_path }}/build.liri.io/favicon.ico"
        mode: 0644

    - name: Create Arch Linux stable repository root
      file: path={{ nginx_html_path }}/repo.liri.io/archlinux/stable state=directory recurse=yes mode=0755
    - name: Create Arch Linux unstable repository root
      file: path={{ nginx_html_path }}/repo.liri.io/archlinux/unstable state=directory recurse=yes mode=0755
    - name: Create nginx configuration directory
      file: path={{ nginx_conf_path }} state=directory recurse=yes mode=0755
    - name: Create nginx logs directory for repo
      file: path={{ nginx_logs_path }}/repo.liri.io state=directory recurse=yes mode=0755
    - name: Copy favicon.ico for repo.liri.io
      get_url:
        url: https://raw.githubusercontent.com/lirios/lirios.github.io/master/favicon.ico
        dest: "{{ nginx_html_path }}/repo.liri.io/favicon.ico"
        mode: 0644

    - name: Create CI artifacts directory
      file: path={{ nginx_html_path }}/repo.liri.io/artifacts state=directory recurse=yes mode=0755
    - name: Create CI artifacts master directory
      file: path={{ nginx_html_path }}/repo.liri.io/artifacts/master state=directory recurse=yes mode=0755
    - name: Create CI artifacts develop directory
      file: path={{ nginx_html_path }}/repo.liri.io/artifacts/develop state=directory recurse=yes mode=0755
