---
- hosts: main
  become: yes
  become_method: sudo
  vars_files:
    - ../vars.yml
  tasks:
    - name: Restart www service
      shell: systemctl daemon-reload && systemctl restart docker@www.service
#      systemd:
#        name: docker@www.service
#        state: started
#        enabled: True
