version: '2'

networks:
  traefik_web:
    external: true

services:
  backend:
    image: liri-docker-registry.bintray.io/library/website:latest
    expose:
      - "8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.www-backend.rule=Host(`api.liri.io`) && PathPrefix(`/backend`)
      - traefik.http.routers.www-backend.entryPoints=websecure
      - traefik.http.routers.www-backend.tls=true
      - traefik.http.routers.www-backend.tls.certresolver=letsencrypt
      - traefik.http.services.www-backend.loadbalancer.server.port=8080
    volumes:
      - /etc/liri/www-go.ini:/config.ini:ro
    networks:
      - traefik_web
    restart: on-failure
  frontend:
    image: liriorg/nginx
    expose:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.www.rule=Host(`repo.liri.io`)
      - traefik.http.routers.www.entryPoints=websecure
      - traefik.http.routers.www.tls=true
      - traefik.http.routers.www.tls.certresolver=letsencrypt
      - traefik.http.services.www.loadbalancer.server.port=80
    volumes:
      - /etc/liri/www/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/liri/www/snippets:/etc/nginx/snippets:ro
      - /srv/www:/usr/share/nginx/html:ro
      - /var/log/nginx:/var/log/nginx
    networks:
      - traefik_web
    restart: on-failure
