- name: "Copy configuration"
  copy: src={{ item.src }} dest={{ item.dest }} mode=0644
  loop:
    - { src: "jenkins.service", dest: "/etc/systemd/system/jenkins.service" }
    - { src: "compose.yml", dest: "/etc/liri/jenkins/docker-compose.yml" }
    - { src: "Dockerfile", dest: "/etc/liri/jenkins/Dockerfile" }

- name: "Restart service"
  shell: systemctl enable jenkins.service && systemctl daemon-reload && systemctl restart jenkins.service
  #systemd: name=jenkins.service state=restarted enabled=True
